name: Get latest release versions

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch flux release version
        run: |
          curl -sL https://api.github.com/repos/fluxcd/flux/releases/latest | \
          jq -r ".tag_name" > build/flux/.version

      # This API endpoint will need to change when helm-operator has an offical release
      - name: Fetch helm-operator release version
        run: |
          curl -sL https://api.github.com/repos/fluxcd/helm-operator/tags | \
          jq -r '.[0].name'

      - name: Fetch gatekeeper release version
        run: |
          curl -sL https://api.github.com/repos/open-policy-agent/gatekeeper/releases/latest | \
          jq -r ".tag_name" > build/gatekeeper/.version

      - name: Fetch kustomize release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest | \
          jq -r ".tag_name" > build/kustomize/.version && \
          VERSION=$(cat build/kustomize/.version | cut -c 11-) && \
          echo $VERSION > build/kustomize/.version

      - name: Fetch sops release version
        run: |
          curl -sL https://api.github.com/repos/mozilla/sops/releases/latest | \
          jq -r ".tag_name" > build/sops/.version

      - name: Fetch pihole release version
        run: |
          curl -sL https://api.github.com/repos/eko/pihole-exporter/releases/latest | \
          jq -r ".tag_name" > build/pihole-exporter/.version

      - name: Fetch kured release version
        run: |
          curl -sL https://api.github.com/repos/weaveworks/kured/releases/latest | \
          jq -r ".tag_name" > build/kured/.version

      - name: Fetch apcupsd-exporter latest git SHA (no version)
        run: |
          curl -sL https://api.github.com/repos/mdlayher/apcupsd_exporter/commits | \
          jq -r '.[0] .sha' > build/apcupsd-exporter/.version
      
      - name: Fetch descheduler release version
        run: |
          curl -sL https://api.github.com/repos/kubernetes-sigs/descheduler/releases/latest | \
          jq -r ".tag_name" > build/descheduler/.version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Michael Fornaro'
          git config --global user.email '20387402+xUnholy@users.noreply.github.com'
          git commit -am "Adding new release version" || exit 0
          git push
